// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdT07aIWKpfjqh3W2oqVttUEFk8Z4DDi8',
    appId: '1:1055468942794:web:af210acfd0c3531d0f0b33',
    messagingSenderId: '1055468942794',
    projectId: 'ecommerce-newwave-hungnt',
    authDomain: 'ecommerce-newwave-hungnt.firebaseapp.com',
    storageBucket: 'ecommerce-newwave-hungnt.appspot.com',
    measurementId: 'G-18KJCHPHP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkBKgDYYENndBW_8kxNFDQaNoDpK8sPpU',
    appId: '1:1055468942794:android:06aece756b21088e0f0b33',
    messagingSenderId: '1055468942794',
    projectId: 'ecommerce-newwave-hungnt',
    storageBucket: 'ecommerce-newwave-hungnt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-ei1SRw5eCptFLrMJFsGQoEEwhqjEGqA',
    appId: '1:1055468942794:ios:48f1125329dbd0570f0b33',
    messagingSenderId: '1055468942794',
    projectId: 'ecommerce-newwave-hungnt',
    storageBucket: 'ecommerce-newwave-hungnt.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-ei1SRw5eCptFLrMJFsGQoEEwhqjEGqA',
    appId: '1:1055468942794:ios:c0bbf59f8d620a9e0f0b33',
    messagingSenderId: '1055468942794',
    projectId: 'ecommerce-newwave-hungnt',
    storageBucket: 'ecommerce-newwave-hungnt.appspot.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
